# Generated by Django 5.0 on 2023-12-27 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Categoria Pokemon',
                'verbose_name_plural': 'Categorias Pokemon',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('color', models.CharField(choices=[('1', 'Rojo'), ('2', 'Amarillo'), ('3', 'Azul'), ('4', 'Naranja'), ('5', 'Verde'), ('6', 'Morado')], max_length=1)),
                ('dateCapture', models.DateTimeField(auto_now_add=True)),
                ('softDelete', models.BooleanField(default=0)),
                ('pokemonImage', models.ImageField(blank=True, null=True, upload_to='PokemonImages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='pokemon.pokemoncategory')),
            ],
        ),
    ]
