# Generated by Django 5.0 on 2023-12-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemonImage',
            field=models.ImageField(null=True, upload_to='PokemonImages'),
        ),
    ]
