# Generated by Django 5.0 on 2024-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_alter_pokemon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='softDelete',
            field=models.BooleanField(default=True),
        ),
    ]
