# Generated by Django 5.0 on 2024-01-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_alter_pokemon_softdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
